portal-projection-view-distance: 16
portal-display-range: 32
hide-portal-blocks: true
cancel-teleport-when-linking-portals: true
debug-messages: false
worlds-with-portal-viewing:
  - world
  - world_nether