portal-projection-view-distance: 8
portal-display-range: 32
hide-portal-blocks: false
cancel-teleport-when-linking-portals: true
worlds-with-projecting-portals:
  - world
viewable-worlds:
  - world_nether