portal-projection-view-distance: 8
portal-display-range: 32
hide-portal-blocks: false
cancel-teleport-when-linking-portals: true
worlds-with-portal-viewing:
  - world
  - world_nether
debug-messages: false