portal-projection-view-distance: 4
portal-display-range: 32
hide-portal-blocks: true
cancel-teleport-when-linking-portals: true
instant-teleport: true
warning-messages: true
debug-messages: false
hide-entities:
  enabled: true
  hide-players: true
worlds-with-portal-viewing:
  - world
  - world_nether