name: NetherView
version: ${project.version}
api-version: 1.13

main: me.gorgeousone.netherview.NetherViewPlugin

softdepend: [ProtocolLib]

commands:
  netherview:
    aliases: [nv]
  toggleportalview:
    description: Toggles whether you can see potal projections or not for yourself.

permissions:
  netherview.viewportals:
    default: true
  netherview.linkportals:
    default: true
  netherview.config:
    default: op
  netherview.info:
    default: op
  netherview.flipportal:
    default: op