name: NetherView
version: ${project.version}
api-version: 1.13

main: me.gorgeousone.netherview.NetherView

depend: [ProtocolLib]

commands:
  netherview:
    aliases: [nv]

permissions:
  netherview.viewportals:
    default: op
  netherview.linkportals:
    default: op
  netherview.reload:
    default: op