name: NetherView
version: ${project.version}
api-version: 1.13

main: me.gorgeousone.netherview.NetherView

softdepend: [ProtocolLib]

commands:
  netherview:
    aliases: [nv]

permissions:
  netherview.viewportals:
    default: true
  netherview.linkportals:
    default: true
  netherview.config:
    default: op
  netherview.info:
    default: op
  netherview.flipportal:
    default: op