name: NetherView
version: ${project.version}
api-version: 1.13

main: me.gorgeousone.netherview.NetherView

softdepend: [ProtocolLib]

commands:
  netherview:
    aliases: [nv]
  d:
    description: debug

permissions:
  netherview.viewportals:
    default: true
  netherview.linkportals:
    default: true
  netherview.reload:
    default: op
  netherview.info:
    default: op