name: NetherView
version: 1.0
api-version: 1.13

main: me.gorgeousone.netherview.Main

commands:
  nvreload:
    description: /<command>

permissions:
  netherview.viewportals:
    default: op
  netherview.linkportals:
    default: op
  netherview.reload:
    default: op